name: Deploy App on AppCenter
on:
  push:
    branches:
      - main
      - 'releases/**'
jobs:
  deploy_iOS:
    uses: ./.github/workflows/deploy_ios.yml
  deploy_android:
    uses: ./.github/workflows/deploy_android.yml
